[package]
name = "pyes"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
phf = { version = "0.11.1", features = ["macros"] }
regex = "1.8.3"
